spring:
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/student_demo"
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: "jdbc:postgresql://localhost:5432/student_demo"
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

---

#database:
#  driver: org.postgresql.Driver
#  url: "jdbc:postgresql://localhost:5432/student_demo"
#  login: postgres
#  password: root

---

security:
  secretKey: top_secret_key_hoho!